language: node_js
cache: true
node_js:
  - "4.1"

branches:
  only:
    - master

before_install:
  - npm install -g eslint
  - npm install grunt -g

script:
  - npm install
  - grunt test 

notifications:
  email:
    - john.patterson@secondphase.com.au